; generated by SuperSlicer 2.3.57 on 2022-02-11 at 21:37:56 UTC


;
; thumbnail begin 48x48 600
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAABh0lEQVR4Ae2Yv0oDQRDGv04bA4JYBJ
; Fgk0BALNJpEYIWFmqq2AQ80EJfwDqglaW95AEEWztTCbY+wT1KZIqT+Ge8vXV3dg7mB9McdzD3zXy7
; wwCGYRiGVnpN9ClQN5oraF32MHm/wpziZoAp6gIl/zxGXiRfBD1TXY3vqnNB70AblPzDCWZlyRdB79
; I30ICL6lwct5EhFa4t41INSMMZ1TfEDB5K9SQGD636X9UIbvCYqketRuyWiWpwMpVEy7i0VCWDp1ad
; C6d5SsqowauhVXUuvhi86hyjJT7nqdVltO4O6vUDr+eY3x8ibywt3BejLiZvF/qTJx8MO8wdQSV5Ot
; Vr4h+qc5zt6DI0tUzlm7m7jv5Llj55apn9Lc+xIqXBSfXbAWZOLVPGUVvW4P9SnUOqGs5G9YWO21gt
; I7axCG3wxxHyzprwzihES5Hq17uJt3Z7m8h8qhHFqL5UrUZ0o/pSZnBSfbytcLW4CDdPTYfINxo1Wr
; UX85To8RgaOm7VGNUwDMP4jQ+Its5Lnx6xvgAAAABJRU5ErkJggg==
; thumbnail end
;

;
; thumbnail begin 300x300 2956
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAIb0lEQVR4Ae3dPYseVRiA4dNpYyBFCm
; OKkBSBdJIgAUGChsAKRhExRRQWP0A7KyuLgIWWW9hYyAq2pgxiYyrB1l+Qn7LmJA4ZdjP7zjvvmZnz
; cV1wN+k2bIbnPMyZhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAA1OP8K+FiAMhdfFj98Ul4HLt+PtwMADn66nq4/+/X4ahf/LMAkIs4VX3/djg8/rDq+uX9
; 8CgArO3OlbAfj39DD6suR0RgNXGqetERcFNxEgsAS+kW69s+rExbwGKmTlVDWcgDs4gPq7g8T/Ww6k
; 9b3tsCkkk5VZm2gFmkPgJuyusPwCS7LtYt5IHZLT1VOSICk6w1VZm2gK3kMFWZtoBT5XIE3JSFPDQu
; HrdyOgI6IgInlDJVDeU+IjQit8W6aQs4ofSpaigLeajMXPcAcyn+bO4jQgVqnKpelCMiFKzWI+CYaS
; sA5ahlsW7agoq1OlUNZSEPmWp9qhrKBwIhM6aqzZm2YGWOgNtlIQ8rKe0eYC5ZyMOCTFVpckSEmVms
; p820BTMxVc2XaQsSiVNV/JxKSQ+AErOQhx3duRL2S/pHX3qOiDCBxfq6+UAgjGSxnkemLTiFqSrPLO
; ThmNo/sFd67iPC/0xV5WTaolmOgGXm9QeaY7FedhbyNMFUVVeOiFTLVFVnpi2qY6qqP9MWxXMEbCsL
; eYrlA3tt5ohIUUxVirmPSPYs1tXPtEWWTFU6LQt5suEeoMYUf0fcR2RVpiptUzwixo8yBliSI6B2ye
; sPLMZiXSmykGdWpirNkYU8yZmqNGc+EEgypiotlWmLyRwBtUYW8mzNPUCtmYU8o5iqlFOOiAyyWFeO
; mbY4wVSl3DNt4R6gispCvmHxTldJv6xSzBGxMRbrqiEfCGyAxbpqyrRVKVOVas5CviIW62oh9xErYK
; pSa5m2CuQIqJbz+kNBLNYlC/nsmaqkkzkiZshUJQ1n2sqIqUoal2lrRY6A0vZZyK/AB/ak6TkiLsRU
; JaXLfcQZWaxL6TNtJWaqkubPQj4B9wCl5Yr/1txHnMhUJa1T/LhlYBxHQGn9vP4wgsW6lE8W8gNMVV
; K+Wcj3mKqk/POBwGCxLpVWk9OWI6BUbk0t5N0DlMqv+oW8qUqqryqPiBbrUr1VM22ZqqR2Knracg9Q
; aq8iF/KmKqndijkiOgJK6sr6A4EW65KOl920ZaqStKksFvKmKkljW/U+oqlK0pQWnbYcASXt2iKvP7
; gHKClVsy3kTVWS5irpEdFiXdLcJZm2TFWSlmzStBWnqviWakk/qKQ62mohH/9PMkdASWs26oh46Wy4
; +dd+WT+YpDr7+/Nw9MZrp/ynrvGB9cOtcPT7x2X9YJLq6tcPwtE3N8LRhTMjpqz40Pr5vbJ+QEnlF6
; eq+LD67PXw+MaFkQv4sy+Hi19eC48O9sKRI6KkJfrz03D03VvPHlZnXppw5/CdS+F+nLZ++7CsH1xS
; OU2aqkxbkpYuPqx2mqqGdNOWhbykXeumqrhY33mqGtJfyP/zRVl/QZLyKD6sfryV6Ai4Sf+I+PBeWX
; 9Rktatm6o+uhoeJT0CbnLt1bDv9QdJY0q6WJ/KQl7SpmZbrE9lIS/peFlMVUPiQv7bN8Pjgz0Lean1
; +lPVxus1a4lHxCfLtEPTltRus7+ukJr7iFJ7ZX0E3MRCXmqnne8B5sJCXqq3oqeqIXHa6hbypi2pjr
; J7XSE105ZUR8Ut1qeykJfKbdF7gLmwkJfK68Hdle4B5sIHAqX8q3KxPpVpS8q36hfrU1nIS/lkqhqh
; W8gf7LmPKK1Vf7Ge7T3AXHRHRNOWtHzd6wq3L4fDwHg+ECgtlyNgAhby0vxZrCdmIS+lz1Q1I/cRpX
; SZqhZi2pJ2q5l7gLlwH1HaPkfAFVnIS+PrPrDX7D3AXLiPKA1nqsqQaUs6mcV65izkpedTlcV6AfoL
; efcR1Vr9e4BXz4X9QP769xEf3ivrF06aWjdVWawXyn1EtZDFekUs5FVzFuuVspBXTZmqGtC/j2ghr1
; LrT1U+sNeAJ0vJQ9OWSszrCo1yH1El5QiIhbyKqLsHaLHOUxbyyjFTFYN8IFA55XUFRjFtac3cA2Rr
; FvJao/49QA8rtmIhryVzD5AkfCBQc2axTnKmLc2RxTqzspBXikxVLCYu5N1H1NTcA2Rx/Q8EmrY0Nq
; 8rsCofCNSYHAHJhoW8Tss9QLJkIa9+piqy5z6iuoeVqYpimLbazWKdIrmP2FZxqvrpXUdACmYh30YP
; 7j47AroHSBXcR6wzi3WqZdqq72FlsU71LOTLf1BZrNOUbiF/sOc+YmkPq+4De1fPhf0ArXAfsay6qe
; r25XAYoFXuI+adxTocYyGf78PKYh0GWMjn86AyVcEI7iOu/7DygT3Ykmlr+byuADtwH3GZHAEhEQv5
; efOBPZiB+4hpM1XBzExb6R5WpipYiIX89AeVxTqsoL+Qdx9x3MOquwfoYQUrcEQcVzdV+cAeZMB9xB
; dnsQ6ZMm2dfFhZrEPmWl/Im6qgMHEh391HbGkh7x4gFKq1DwR6XQEqUPt9REdAqEytC3n3AKFitSzk
; TVXQiNI/EOh1BWhQidOWxTo0rJSFvHuAwFO5L+Qf3HUPEDgmtw8EWqwDp8pl2rJYB0ZbayHvA3vAJN
; 1CPk5bS9xH7C/W3QMEtrbUfcRuqrp9ORwGgF3M9YFAi3VgFqkX8hbrwOx2XcibqoBFTb2P6AN7wGq2
; mba8rgCsbtN9REdAICtDC3kf2AOy1b+PaKoCstdNW6YqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgHf8BznDkP/AcS80AAAAASUVORK5CYII=
; thumbnail end
;
; 

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.72mm
; solid infill extrusion width = 0.56mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.42mm
; first layer extrusion width = 0.48mm

; object:{"name":"Patch-25x25x0","id":"Patch-25x25x0.25mm.stl id:0 copy 0","object_center":[165.000000,165.000000,0.000000],"boundingbox_center":[165.000000,165.000000,0.125000],"boundingbox_size":[25.000000,25.000000,0.250000]}
; plater:{"center":[165.000000,165.000000,0.000000],"boundingbox_center":[165.000000,165.000000,0.125000],"boundingbox_size":[25.000000,25.000000,0.250000]}

;TYPE:Custom
START_PRINT T_BED=60 T_EXTRUDER=200
M107
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
M104 S200 ; set temperature
M109 S200 ; set temperature and wait for it to be reached
M190 S60 ; set bed temperature and wait for it to be reached
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 E-0.6 F3000
G1 Z0.2 F9000
G1 X149.845 Y150.197
G1 E0.6 F1800
; External perimeter
;Skirt
SET_VELOCITY_LIMIT ACCEL=4000 ACCEL_TO_DECEL=4000 SQUARE_CORNER_VELOCITY=8

; Support material

;TYPE:Skirt
;WIDTH:0.48
G1 X149.475 Y150.704 E0.0228
G1 X149.198 Y151.262 E0.02263
G1 X149.019 Y151.863 E0.0228
G1 X148.946 Y152.482 E0.02263
G1 X148.945 Y177.441 E0.90709
G1 X149.034 Y178.204 E0.02793
G1 X149.281 Y178.932 E0.02793
G1 X149.674 Y179.592 E0.02793
G1 X150.197 Y180.155 E0.02793
G1 X150.704 Y180.525 E0.0228
G1 X151.262 Y180.802 E0.02263
G1 X151.863 Y180.981 E0.0228
G1 X152.482 Y181.054 E0.02263
G1 X177.441 Y181.055 E0.90709
G1 X178.204 Y180.966 E0.02793
G1 X178.932 Y180.719 E0.02793
G1 X179.592 Y180.326 E0.02793
G1 X180.155 Y179.803 E0.02793
G1 X180.525 Y179.296 E0.0228
G1 X180.802 Y178.738 E0.02263
G1 X180.981 Y178.137 E0.0228
G1 X181.054 Y177.518 E0.02263
G1 X181.041 Y152.276 E0.91738
G1 X180.92 Y151.613 E0.02451
G1 X180.678 Y150.983 E0.02451
G1 X180.326 Y150.408 E0.02451
G1 X179.869 Y149.905 E0.02468
G1 X179.328 Y149.494 E0.02468
G1 X178.725 Y149.193 E0.02451
G1 X178.076 Y149.007 E0.02451
G1 X177.405 Y148.944 E0.02451
G1 X152.432 Y148.948 E0.9076
G1 X151.704 Y149.056 E0.02674
G1 X151.008 Y149.309 E0.02691
G1 X150.382 Y149.694 E0.02674
G1 X149.889 Y150.156 E0.02455
G1 X150.19 Y150.467 F9000
G1 F1800
G1 X149.858 Y150.915 E0.02027
G1 X149.608 Y151.414 E0.02027
G1 X149.448 Y151.949 E0.02027
G1 X149.383 Y152.503 E0.02027
G1 X149.382 Y177.43 E0.90593
G1 X149.458 Y178.098 E0.02444
G1 X149.672 Y178.735 E0.02444
G1 X150.013 Y179.315 E0.02444
G1 X150.467 Y179.81 E0.02444
G1 X150.915 Y180.142 E0.02027
G1 X151.414 Y180.392 E0.02027
G1 X151.949 Y180.552 E0.02027
G1 X152.503 Y180.617 E0.02027
G1 X177.43 Y180.618 E0.90593
G1 X178.098 Y180.542 E0.02444
G1 X178.735 Y180.328 E0.02444
G1 X179.315 Y179.987 E0.02444
G1 X179.81 Y179.533 E0.02444
G1 X180.142 Y179.085 E0.02027
G1 X180.392 Y178.586 E0.02027
G1 X180.552 Y178.051 E0.02027
G1 X180.617 Y177.493 E0.02043
G1 X180.608 Y152.345 E0.91398
G1 X180.506 Y151.756 E0.02171
G1 X180.296 Y151.196 E0.02171
G1 X179.987 Y150.685 E0.02171
G1 X179.585 Y150.237 E0.02188
G1 X179.111 Y149.874 E0.02171
G1 X178.573 Y149.603 E0.02187
G1 X177.999 Y149.438 E0.02171
G1 X177.404 Y149.381 E0.02171
G1 X152.473 Y149.384 E0.90609
G1 X151.833 Y149.474 E0.02348
G1 X151.22 Y149.692 E0.02364
G1 X150.668 Y150.026 E0.02348
G1 X150.234 Y150.427 E0.02146
; INIT printing object Patch-25x25x0.25mm.stl id:0 copy 0
G1 E-0.6 F3000
; printing object Patch-25x25x0.25mm.stl id:0 copy 0
G1 X152.84 Y152.84 F9000
G1 E0.6 F1800
; External perimeter
;ExternalPerimeter
SET_VELOCITY_LIMIT ACCEL=1000 ACCEL_TO_DECEL=1000 SQUARE_CORNER_VELOCITY=8

; Perimeter

;TYPE:External perimeter
G1 X177.16 Y152.84 E0.88387
G1 X177.16 Y152.96 E0.00389
G1 X177.16 Y153.2 E0.00825
G1 X177.16 Y177.16 E0.87079
G1 X177.04 Y177.16 E0.00389
G1 X176.8 Y177.16 E0.00825
G1 X152.84 Y177.16 E0.87079
G1 X152.84 Y177.04 E0.00389
G1 X152.84 Y176.8 E0.00825
G1 X152.84 Y152.9 E0.86861
;WIPE_START
G1 X153.186 Y153.04 F9000
;WIPE_END
G1 X176.211 Y152.906
; External perimeter
;SolidInfill
SET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=2000 SQUARE_CORNER_VELOCITY=8

; Bridge infill

;TYPE:Solid infill
;WIDTH:0.47415
G1 F2400
G1 X176.907 Y153.601 E0.03532
G1 X176.907 Y154.219 E0.02219
G1 X175.781 Y153.093 E0.05716
G1 X175.163 Y153.093 E0.02219
G1 X176.907 Y154.837 E0.08854
G1 X176.907 Y155.456 E0.02219
G1 X174.544 Y153.093 E0.11992
G1 X173.926 Y153.093 E0.02219
G1 X176.907 Y156.074 E0.1513
G1 X176.907 Y156.692 E0.02219
G1 X173.308 Y153.093 E0.18269
G1 X172.69 Y153.093 E0.02219
G1 X176.907 Y157.31 E0.21407
G1 X176.907 Y157.928 E0.02219
G1 X172.072 Y153.093 E0.24545
G1 X171.454 Y153.093 E0.02219
G1 X176.907 Y158.546 E0.27684
G1 X176.907 Y159.164 E0.02219
G1 X170.836 Y153.093 E0.30822
G1 X170.218 Y153.093 E0.02219
G1 X176.907 Y159.782 E0.3396
G1 X176.907 Y160.4 E0.02219
G1 X169.6 Y153.093 E0.37098
G1 X168.981 Y153.093 E0.02219
G1 X176.907 Y161.019 E0.40237
G1 X176.907 Y161.637 E0.02219
G1 X168.363 Y153.093 E0.43375
G1 X167.745 Y153.093 E0.02219
G1 X176.907 Y162.255 E0.46513
G1 X176.907 Y162.873 E0.02219
G1 X167.127 Y153.093 E0.49651
G1 X166.509 Y153.093 E0.02219
G1 X176.907 Y163.491 E0.5279
G1 X176.907 Y164.109 E0.02219
G1 X165.891 Y153.093 E0.55928
G1 X165.273 Y153.093 E0.02219
G1 X176.907 Y164.727 E0.59066
G1 X176.907 Y165.345 E0.02219
G1 X164.655 Y153.093 E0.62204
G1 X164.036 Y153.093 E0.02219
G1 X176.907 Y165.964 E0.65343
G1 X176.907 Y166.582 E0.02219
G1 X163.418 Y153.093 E0.68481
G1 X162.8 Y153.093 E0.02219
G1 X176.907 Y167.2 E0.71619
G1 X176.907 Y167.818 E0.02219
G1 X162.182 Y153.093 E0.74757
G1 X161.564 Y153.093 E0.02219
G1 X176.907 Y168.436 E0.77896
G1 X176.907 Y169.054 E0.02219
G1 X160.946 Y153.093 E0.81034
G1 X160.328 Y153.093 E0.02219
G1 X176.907 Y169.672 E0.84172
G1 X176.907 Y170.29 E0.02219
G1 X159.71 Y153.093 E0.8731
G1 X159.091 Y153.093 E0.02219
G1 X176.907 Y170.909 E0.90449
G1 X176.907 Y171.527 E0.02219
G1 X158.473 Y153.093 E0.93587
G1 X157.855 Y153.093 E0.02219
G1 X176.907 Y172.145 E0.96725
G1 X176.907 Y172.763 E0.02219
G1 X157.237 Y153.093 E0.99864
G1 X156.619 Y153.093 E0.02219
G1 X176.907 Y173.381 E1.03002
G1 X176.907 Y173.999 E0.02219
G1 X156.001 Y153.093 E1.0614
G1 X155.383 Y153.093 E0.02219
G1 X176.907 Y174.617 E1.09278
G1 X176.907 Y175.235 E0.02219
G1 X154.765 Y153.093 E1.12417
G1 X154.146 Y153.093 E0.02219
G1 X176.907 Y175.854 E1.15555
G1 X176.907 Y176.472 E0.02219
G1 X153.528 Y153.093 E1.18693
G1 X153.093 Y153.093 E0.01561
G1 X153.093 Y153.277 E0.00658
G1 X176.723 Y176.907 E1.1997
G1 X176.105 Y176.907 E0.02219
G1 X153.093 Y153.895 E1.16832
G1 X153.093 Y154.513 E0.02219
G1 X175.487 Y176.907 E1.13694
G1 X174.869 Y176.907 E0.02219
G1 X153.093 Y155.131 E1.10555
G1 X153.093 Y155.749 E0.02219
G1 X174.251 Y176.907 E1.07417
G1 X173.633 Y176.907 E0.02219
G1 X153.093 Y156.367 E1.04279
G1 X153.093 Y156.986 E0.02219
G1 X173.014 Y176.907 E1.0114
G1 X172.396 Y176.907 E0.02219
G1 X153.093 Y157.604 E0.98002
G1 X153.093 Y158.222 E0.02219
G1 X171.778 Y176.907 E0.94864
G1 X171.16 Y176.907 E0.02219
G1 X153.093 Y158.84 E0.91726
G1 X153.093 Y159.458 E0.02219
G1 X170.542 Y176.907 E0.88587
G1 X169.924 Y176.907 E0.02219
G1 X153.093 Y160.076 E0.85449
G1 X153.093 Y160.694 E0.02219
G1 X169.306 Y176.907 E0.82311
G1 X168.688 Y176.907 E0.02219
G1 X153.093 Y161.312 E0.79173
G1 X153.093 Y161.931 E0.02219
G1 X168.069 Y176.907 E0.76034
G1 X167.451 Y176.907 E0.02219
G1 X153.093 Y162.549 E0.72896
G1 X153.093 Y163.167 E0.02219
G1 X166.833 Y176.907 E0.69758
G1 X166.215 Y176.907 E0.02219
G1 X153.093 Y163.785 E0.6662
G1 X153.093 Y164.403 E0.02219
G1 X165.597 Y176.907 E0.63481
G1 X164.979 Y176.907 E0.02219
G1 X153.093 Y165.021 E0.60343
G1 X153.093 Y165.639 E0.02219
G1 X164.361 Y176.907 E0.57205
G1 X163.743 Y176.907 E0.02219
G1 X153.093 Y166.257 E0.54067
G1 X153.093 Y166.875 E0.02219
G1 X163.125 Y176.907 E0.50928
G1 X162.506 Y176.907 E0.02219
G1 X153.093 Y167.494 E0.4779
G1 X153.093 Y168.112 E0.02219
G1 X161.888 Y176.907 E0.44652
G1 X161.27 Y176.907 E0.02219
G1 X153.093 Y168.73 E0.41514
G1 X153.093 Y169.348 E0.02219
G1 X160.652 Y176.907 E0.38375
G1 X160.034 Y176.907 E0.02219
G1 X153.093 Y169.966 E0.35237
G1 X153.093 Y170.584 E0.02219
G1 X159.416 Y176.907 E0.32099
G1 X158.798 Y176.907 E0.02219
G1 X153.093 Y171.202 E0.2896
G1 X153.093 Y171.82 E0.02219
G1 X158.18 Y176.907 E0.25822
G1 X157.561 Y176.907 E0.02219
G1 X153.093 Y172.439 E0.22684
G1 X153.093 Y173.057 E0.02219
G1 X156.943 Y176.907 E0.19546
G1 X156.325 Y176.907 E0.02219
G1 X153.093 Y173.675 E0.16407
G1 X153.093 Y174.293 E0.02219
G1 X155.707 Y176.907 E0.13269
G1 X155.089 Y176.907 E0.02219
G1 X153.093 Y174.911 E0.10131
G1 X153.093 Y175.529 E0.02219
G1 X154.471 Y176.907 E0.06993
G1 X153.853 Y176.907 E0.02219
G1 X153.093 Y176.147 E0.03854
G1 X153.093 Y176.765 E0.02219
G1 X153.422 Y177.094 E0.0167
; INIT stop printing object Patch-25x25x0.25mm.stl id:0 copy 0
G1 E-0.6 F3000
; stop printing object Patch-25x25x0.25mm.stl id:0 copy 0
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
END_PRINT
; filament used [mm] = 60.58
; filament used [cm3] = 0.15
; filament used [g] = 0.18
; filament cost = 0.01
; total filament used [g] = 0.18
; total filament cost = 0.01
; total layers count = 1
; estimated printing time (normal mode) = 52s

; allow_empty_layers = 0
; avoid_crossing_not_first_layer = 1
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,330x0,330x330,0x330
; bed_temperature = 60
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = monotonicgapfill
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 1
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 85%
; bridge_internal_fan_speed = -1
; bridge_overlap = 50%
; bridge_overlap_min = 50%
; bridge_speed = 30
; bridge_speed_internal = 120
; bridged_infill_margin = 200%
; brim_ears = 0
; brim_ears_detection_length = 1
; brim_ears_max_angle = 120
; brim_ears_pattern = concentric
; brim_inside_holes = 0
; brim_offset = 0
; brim_width = 0
; brim_width_interior = 0
; chamber_temperature = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; complete_objects_one_brim = 0
; complete_objects_one_skirt = 0
; complete_objects_sort = object
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; curve_smoothing_angle_concave = 160
; curve_smoothing_angle_convex = 160
; curve_smoothing_cutoff_dist = 2
; curve_smoothing_precision = 0
; default_acceleration = 0
; default_filament_profile = ""
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 5
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 1
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = END_PRINT
; enforce_full_fill_volume = 1
; ensure_vertical_shell_thickness = 1
; exact_last_layer_height = 0
; external_infill_margin = 150%
; external_perimeter_cut_corners = 100%
; external_perimeter_extrusion_spacing = 
; external_perimeter_extrusion_width = 100%
; external_perimeter_fan_speed = -1
; external_perimeter_overlap = 100%
; external_perimeter_speed = 70
; external_perimeters_first = 0
; external_perimeters_hole = 1
; external_perimeters_nothole = 1
; external_perimeters_vase = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_odd_layers = 0
; extra_perimeters_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_fan_offset = 0%
; extruder_offset = 0x0
; extruder_temperature_offset = 0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_spacing = 
; extrusion_width = 0
; fan_always_on = 1
; fan_below_layer_time = 30
; fan_kickstart = 0
; fan_percentage = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; feature_gcode = ; External perimeter\n{if extrusion_role=~/ExternalPerimeter/};[extrusion_role]\nSET_VELOCITY_LIMIT ACCEL=1000 ACCEL_TO_DECEL=1000 SQUARE_CORNER_VELOCITY=8\n\n; Perimeter\n{elsif extrusion_role=~/Perimeter/};[extrusion_role]\nSET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=2000 SQUARE_CORNER_VELOCITY=8\n\n; Overhang perimeter\n{elsif extrusion_role=~/OverhangPerimeter/};[extrusion_role]\nSET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=2000 SQUARE_CORNER_VELOCITY=8\n\n; Internal infill\n{elsif extrusion_role=~/InternalInfill/};[extrusion_role]\nSET_VELOCITY_LIMIT ACCEL=4000 ACCEL_TO_DECEL=2000 SQUARE_CORNER_VELOCITY=8\n\n; Top solid infill\n{elsif extrusion_role=~/TopSolidInfill/};[extrusion_role]\nSET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=2000 SQUARE_CORNER_VELOCITY=8\n\n; Solid infill\n{elsif extrusion_role=~/SolidInfill/};[extrusion_role]\nSET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=2000 SQUARE_CORNER_VELOCITY=8\n\n; Bridge infill\n{elsif extrusion_role=~/BridgeInfill/};[extrusion_role]\nSET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=2000 SQUARE_CORNER_VELOCITY=8\n\n; Gap fill\n{elsif extrusion_role=~/GapFill/};[extrusion_role]\nSET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=2000 SQUARE_CORNER_VELOCITY=8\n\n; Skirt\n{elsif extrusion_role=~/Skirt/};[extrusion_role]\nSET_VELOCITY_LIMIT ACCEL=4000 ACCEL_TO_DECEL=4000 SQUARE_CORNER_VELOCITY=8\n\n; Support material\n{elsif extrusion_role=~/SupportMaterial/};[extrusion_role]\nSET_VELOCITY_LIMIT ACCEL=3000 ACCEL_TO_DECEL=3000 SQUARE_CORNER_VELOCITY=8\n\n; Support material interface\n{elsif extrusion_role=~/SupportMaterialInterface/};[extrusion_role]\nSET_VELOCITY_LIMIT ACCEL=3000 ACCEL_TO_DECEL=3000 SQUARE_CORNER_VELOCITY=8\n\n; Thin walls\n{elsif extrusion_role=~/ThinWall/};[extrusion_role]\nSET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=2000 SQUARE_CORNER_VELOCITY=8\n\n; Other\n{else};[extrusion_role]\nSET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=2000 SQUARE_CORNER_VELOCITY=8\n{endif}
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cooling_zone_pause = 0
; filament_cost = 30
; filament_custom_variables = ""
; filament_density = 1.24
; filament_deretract_speed = 30
; filament_diameter = 1.75
; filament_dip_extraction_speed = 70
; filament_dip_insertion_speed = 33
; filament_enable_toolchange_part_fan = 0
; filament_enable_toolchange_temp = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_overlap = 100%
; filament_max_speed = 0
; filament_max_volumetric_speed = 0
; filament_max_wipe_tower_speed = 0
; filament_melt_zone_pause = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_length = 0.6
; filament_retract_speed = 50
; filament_settings_id = PLA
; filament_shrink = 100%
; filament_skinnydip_distance = 31
; filament_soluble = 0
; filament_spool_weight = 1000
; filament_toolchange_delay = 0
; filament_toolchange_part_fan_speed = 50
; filament_toolchange_temp = 200
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_use_fast_skinnydip = 0
; filament_use_skinnydip = 0
; filament_vendor = (Unknown)
; filament_wipe_advanced_pigment = 0.5
; fill_angle = 45
; fill_angle_increment = 0
; fill_density = 23%
; fill_pattern = rectilinear
; fill_smooth_distribution = 15%
; fill_smooth_width = 50%
; fill_top_flow_ratio = 100%
; first_layer_acceleration = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_spacing = 
; first_layer_extrusion_width = 120%
; first_layer_flow_ratio = 100%
; first_layer_height = 0.2
; first_layer_infill_speed = 40
; first_layer_min_speed = 0
; first_layer_size_compensation = -0.1
; first_layer_size_compensation_layers = 2
; first_layer_speed = 30
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; gap_fill = 1
; gap_fill_last = 1
; gap_fill_min_area = 50%
; gap_fill_overlap = 100%
; gap_fill_speed = 30
; gcode_comments = 0
; gcode_filename_illegal_char = 
; gcode_flavor = klipper
; gcode_label_objects = 1
; gcode_precision_e = 5
; gcode_precision_xyz = 3
; high_current_on_filament_swap = 0
; hole_size_compensation = 0
; hole_size_threshold = 100
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 0
; infill_connection = connected
; infill_connection_bottom = connected
; infill_connection_solid = connected
; infill_connection_top = connected
; infill_dense = 0
; infill_dense_algo = autosmall
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_spacing = 
; infill_extrusion_width = 180%
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 40%
; infill_speed = 0
; interface_shells = 0
; ironing = 0
; ironing_angle = -1
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.2
; lift_min = 0
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 500,5000
; machine_max_acceleration_retracting = 500,5000
; machine_max_acceleration_travel = 2500,1000
; machine_max_acceleration_x = 3000,1000
; machine_max_acceleration_y = 3000,1000
; machine_max_acceleration_z = 100,100
; machine_max_feedrate_e = 25,25
; machine_max_feedrate_x = 300,300
; machine_max_feedrate_y = 300,300
; machine_max_feedrate_z = 5,5
; machine_max_jerk_e = 5,5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.3,0.3
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 80
; max_gcode_per_second = 1500
; max_layer_height = 0
; max_print_height = 400
; max_print_speed = 150
; max_speed_reduction = 90%
; max_volumetric_speed = 15
; milling_after_z = 200%
; milling_extra_size = 150%
; milling_post_process = 0
; milling_speed = 30
; milling_toolchange_end_gcode = 
; milling_toolchange_start_gcode = 
; min_fan_speed = 90
; min_layer_height = 0.07
; min_length = 0.035
; min_print_speed = 10
; min_skirt_length = 20
; min_width_top_surface = 200%
; model_precision = 0.0001
; no_perimeter_unsupported_algo = none
; notes = 
; nozzle_diameter = 0.4
; only_one_perimeter_first_layer = 0
; only_one_perimeter_top = 1
; only_one_perimeter_top_other_algo = 0
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base]-[printer_settings_id]-[filament_settings_id].gcode
; over_bridge_flow_ratio = 100%
; overhangs_reverse = 0
; overhangs_reverse_threshold = 250%
; overhangs_speed = 100%
; overhangs_width = 75%
; overhangs_width_speed = 0
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_bonding = 0%
; perimeter_extruder = 1
; perimeter_extrusion_spacing = 
; perimeter_extrusion_width = 0
; perimeter_loop = 0
; perimeter_loop_seam = rear
; perimeter_overlap = 100%
; perimeter_round_corners = 0
; perimeter_speed = 100
; perimeters = 3
; physical_printer_settings_id = TronXY X5SA
; post_process = 
; print_custom_variables = 
; print_extrusion_multiplier = 100%
; print_retract_length = -1
; print_retract_lift = -1
; print_settings_id = TronXY X5SA
; print_temperature = 0
; printer_custom_variables = 
; printer_model = 
; printer_notes = 
; printer_settings_id = TronXY X5SA
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_layers = 0
; remaining_times = 0
; remaining_times_type = m73
; resolution = 0.0125
; resolution_internal = 0.2
; retract_before_travel = 1.5
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_first_layer = 0
; retract_lift_top = "All surfaces"
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 45
; seam_angle_cost = 100%
; seam_gap = 15%
; seam_position = cost
; seam_travel_cost = 0%
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_brim = 0
; skirt_distance = 3
; skirt_distance_from_brim = 1
; skirt_extrusion_width = 0
; skirt_height = 1
; skirts = 2
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 10
; small_perimeter_max_length = 20
; small_perimeter_min_length = 6
; small_perimeter_speed = 30
; solid_fill_pattern = monotonic
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_spacing = 
; solid_infill_extrusion_width = 140%
; solid_infill_speed = 80
; solid_over_perimeters = 2
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = START_PRINT T_BED=[first_layer_bed_temperature] T_EXTRUDER=[first_layer_temperature]
; start_gcode_manual = 0
; support_material = 1
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance_bottom = 0.3
; support_material_contact_distance_top = 0.35
; support_material_contact_distance_type = plane
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 0
; support_material_pattern = rectilinear
; support_material_solid_first_layer = 0
; support_material_spacing = 3
; support_material_speed = 40
; support_material_synchronize_layers = 0
; support_material_threshold = 65
; support_material_with_sheath = 0
; support_material_xy_spacing = 150%
; temperature = 200
; template_custom_gcode = 
; thin_perimeters = 1
; thin_perimeters_all = 0
; thin_walls = 1
; thin_walls_merge = 1
; thin_walls_min_width = 33%
; thin_walls_overlap = 50%
; thin_walls_speed = 30
; threads = 8
; thumbnails = 48x48,300x300
; thumbnails_color = #018aff
; thumbnails_custom_color = 0
; thumbnails_end_file = 0
; thumbnails_with_bed = 0
; time_estimation_compensation = 100%
; tool_name = ""
; toolchange_gcode = 
; top_fan_speed = -1
; top_fill_pattern = monotonicgapfill
; top_infill_extrusion_spacing = 
; top_infill_extrusion_width = 100%
; top_solid_infill_speed = 80
; top_solid_layers = 3
; top_solid_min_thickness = 1
; travel_acceleration = 1500
; travel_speed = 150
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 0
; wipe = 0
; wipe_advanced = 0
; wipe_advanced_algo = linear
; wipe_advanced_multiplier = 60
; wipe_advanced_nozzle_melted_volume = 120
; wipe_extra_perimeter = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_only_crossing = 1
; wipe_speed = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim = 150%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_inner_size_compensation = 0
; xy_size_compensation = 0
; z_offset = 0
; z_step = 0.005
